/***************************************************************************/
/*                                                                         */
/*  sym.java                                                               */
/*                                                                         */
/*  Copyright (c) 2009 Mark-Jan Nederhof                                   */
/*                                                                         */
/*  This file is part of the implementation of PhilologEG, and may only be */
/*  used, modified, and distributed under the terms of the                 */
/*  GNU General Public License (see doc/GPL.TXT).                          */
/*  By continuing to use, modify, or distribute this file you indicate     */
/*  that you have read the license and understand and accept it fully.     */
/*                                                                         */
/***************************************************************************/


//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jan 06 16:58:26 GMT 2009
//----------------------------------------------------

package nederhof.res;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CARET = 9;
  public static final int ASTERISK = 6;
  public static final int NAT_NUM = 23;
  public static final int CLOSE = 5;
  public static final int PERIOD = 7;
  public static final int ERROR = 24;
  public static final int NAME = 20;
  public static final int COLON = 3;
  public static final int MODIFY = 18;
  public static final int STRING = 21;
  public static final int EQUALS = 13;
  public static final int COMMA = 8;
  public static final int INSERT = 17;
  public static final int EOF = 0;
  public static final int EXCLAM = 10;
  public static final int MINUS = 2;
  public static final int error = 1;
  public static final int OPEN = 4;
  public static final int REAL = 22;
  public static final int STACK = 16;
  public static final int SQ_OPEN = 11;
  public static final int SQ_CLOSE = 12;
  public static final int WHITESPACE = 14;
  public static final int GLYPH_NAME = 19;
  public static final int EMPTY = 15;
}

