#!/usr/bin/env python3
"""Align Unicode 18 Small Seal (U+3D000..3FC3F) with the Oracular oracle-bone PUA font via their shared modern hanzi."""
import re
from collections import defaultdict
from pathlib import Path
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parent.parent
SEAL_SOURCES = ROOT / "dicts/unicode18/SealSources.txt"
ORACLE_PUA_FONT = ROOT / "fonts/oracle_bone_script_F5000.ttf"
ORACLE_DIRECT_FONT = ROOT / "fonts/OracleBoneScript_Oracular.ttf"
SEAL_FONT = ROOT / "fonts/seal-scripts/kaiyuan/fonts/KaiyuanSmallSeal-Regular.ttf"
UNIHAN_READINGS = ROOT / "chinese/Unihan_Readings.txt"
FREQUENCY_LIST = ROOT / "dicts/chinese.freq.tsv"
CURATED_ORACLE_NOTES = ROOT / "docs/oracle.md"
OUTPUT = ROOT / "docs/oracle_seal.md"
HTML_OUTPUT = ROOT / "fonts/oracle_seal.html"
PUA_START = 0xF0000
GLYPH_NAME_CODEPOINT = re.compile(r"^(?:uni|u|H)([0-9A-F]{4,6})$")


def is_hanzi(codepoint):
    return 0x3400 <= codepoint <= 0x9FFF or 0xF900 <= codepoint <= 0xFAFF or 0x20000 <= codepoint <= 0x3134F


def seal_by_hanzi():
    mapping = defaultdict(list)
    for line in SEAL_SOURCES.read_text().splitlines():
        fields = line.split("\t")
        if len(fields) == 3 and fields[1] == "kSEAL_MCJK":
            for modern in fields[2].split():
                mapping[chr(int(modern, 16))].append(chr(int(fields[0][2:], 16)))
    return mapping


def oracle_pua_by_hanzi():
    mapping = defaultdict(list)
    for codepoint, glyph_name in sorted(TTFont(ORACLE_PUA_FONT).getBestCmap().items()):
        match = GLYPH_NAME_CODEPOINT.match(glyph_name)
        if codepoint >= PUA_START and match and is_hanzi(int(match.group(1), 16)):
            mapping[chr(int(match.group(1), 16))].append(chr(codepoint))
    return mapping


def unihan_field(field):
    values = {}
    for line in UNIHAN_READINGS.read_text().splitlines():
        parts = line.split("\t")
        if len(parts) == 3 and parts[1] == field:
            values[chr(int(parts[0].split()[0][2:], 16))] = parts[2]
    return values


def frequency_rank():
    ranks = {}
    for line in FREQUENCY_LIST.read_text().splitlines():
        parts = line.split("\t")
        if len(parts) > 1 and len(parts[1]) == 1 and parts[0].isdigit():
            ranks.setdefault(parts[1], int(parts[0]))
    return ranks


def codepoints(chars):
    return " ".join(f"U+{ord(c):X}" for c in chars)


def table_row(hanzi, oracle, seal, pinyin, gloss, in_notes):
    return f"| {hanzi} | {pinyin.get(hanzi, '')} | {''.join(oracle)} | {''.join(seal)} | {codepoints(oracle)} | {codepoints(seal)} | {'✓' if in_notes else ''} | {gloss.get(hanzi, '')[:40]} |"


HTML_TEMPLATE = """<!doctype html><meta charset="utf-8"><title>Oracle ⇔ Seal</title>
<style>
@font-face {{ font-family: Oracle; src: url(oracle_bone_script_F5000.ttf); }}
@font-face {{ font-family: Seal; src: url(seal-scripts/kaiyuan/fonts/KaiyuanSmallSeal-Regular.ttf); }}
body {{ font-family: sans-serif; margin: 1em; }}
table {{ border-collapse: collapse; }} td, th {{ border-bottom: 1px solid #ddd; padding: 2px 8px; }}
td:nth-child(3) {{ font-family: Oracle; font-size: 40px; }} td:nth-child(4) {{ font-family: Seal; font-size: 40px; }}
</style>
<h1>Oracle bone ⇔ Small Seal (Unicode 18)</h1><p>Generated by scripts/align_seal_oracle.py from docs/oracle_seal.md.</p>
<table>{rows}</table>
"""


def markdown_table_to_html(lines):
    cells = [line.split("|")[1:-1] for line in lines if line.startswith("| ") and not line.startswith("|---")]
    return "".join("<tr>" + "".join(f"<td>{cell.strip()}</td>" for cell in row) + "</tr>" for row in cells)


def main():
    seal = seal_by_hanzi()
    oracle = oracle_pua_by_hanzi()
    direct_oracle = {chr(c) for c in TTFont(ORACLE_DIRECT_FONT).getBestCmap() if is_hanzi(c)}
    seal_rendered = {chr(c) for c in TTFont(SEAL_FONT).getBestCmap()}
    pinyin, gloss, rank = unihan_field("kMandarin"), unihan_field("kDefinition"), frequency_rank()
    shared = sorted(set(seal) & set(oracle), key=lambda h: (rank.get(h, 10**6), h))
    oracle_to_hanzi = {pua: hanzi for hanzi, puas in oracle.items() for pua in puas}
    curated = dict.fromkeys(c for c in CURATED_ORACLE_NOTES.read_text() if ord(c) >= PUA_START)
    curated_shared = dict.fromkeys(oracle_to_hanzi[c] for c in curated if oracle_to_hanzi.get(c) in seal)
    seal_missing_glyph = sum(1 for chars in seal.values() for c in chars if c not in seal_rendered)

    lines = [
        "# Oracle bone ⇔ Small Seal (Unicode 18) alignment",
        "",
        "Generated by `scripts/align_seal_oracle.py`, do not edit by hand.",
        "",
        "Unicode 18.0 (Sept 2026) encodes 11,328 Small Seal 小篆 characters as their own script at U+3D000..U+3FC3F;",
        "oracle bone script 甲骨文 is still unencoded, so the oracle column uses the Oracular PUA font (U+F5000…).",
        "Rows are joined on the modern hanzi: `kSEAL_MCJK` in `dicts/unicode18/SealSources.txt` for seal,",
        "the `uniXXXX`/`uXXXXX` glyph names in `fonts/oracle_bone_script_F5000.ttf` for oracle.",
        "",
        "Fonts: oracle `fonts/oracle_bone_script_F5000.ttf`, seal `fonts/seal-scripts/kaiyuan/fonts/KaiyuanSmallSeal-Regular.ttf` (Kaiyuan Small Seal, OFL).",
        "",
        "## Stats",
        f"- seal characters with a modern equivalent: {sum(map(len, seal.values()))} ({len(seal)} distinct hanzi)",
        f"- seal codepoints the Kaiyuan font has no glyph for yet: {seal_missing_glyph}",
        f"- oracle PUA glyphs named after a hanzi: {sum(map(len, oracle.values()))} ({len(oracle)} distinct hanzi); Oracular also draws {len(direct_oracle)} hanzi at their own codepoint",
        f"- hanzi with both an oracle and a seal form: **{len(shared)}**",
        f"- oracle signs in `docs/oracle.md` whose hanzi has a seal form: {len(curated_shared)}",
        "",
        "## Alignment (by modern frequency; ✓ = oracle sign already used in docs/oracle.md)",
        "",
        "| hanzi | pinyin | oracle | seal | oracle PUA | seal U+ | notes | gloss |",
        "|---|---|---|---|---|---|---|---|",
        *(table_row(h, oracle[h], seal[h], pinyin, gloss, h in curated_shared) for h in shared),
        "",
    ]
    OUTPUT.write_text("\n".join(lines))
    HTML_OUTPUT.write_text(HTML_TEMPLATE.format(rows=markdown_table_to_html(lines)))
    print(f"wrote {OUTPUT.relative_to(ROOT)}: {len(shared)} shared, {len(curated_shared)} curated")


if __name__ == "__main__":
    main()
